// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionLedger.Data;

#nullable disable

namespace TransactionLedger.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904184819_AddTransactions")]
    partial class AddTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionLedger.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Accounts_UserId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_BalanceNonNegative", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("TransactionLedger.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Transactions");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Transactions_Reverses")
                        .HasFilter("\"ReversesTransactionId\" IS NOT NULL");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("IX_Transactions_TransferId")
                        .HasFilter("\"TransferId\" IS NOT NULL");

                    b.HasIndex("AccountId", "Category")
                        .HasDatabaseName("IX_Transactions_Account_Category");

                    b.HasIndex("AccountId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Transactions_Account_Occurred");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_AmountMax", "\"Amount\" <= 1000000000");

                            t.HasCheckConstraint("CK_Transactions_AmountPositive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Transactions_NotSelfReversing", "\"ReversesTransactionId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("TransactionLedger.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TransactionLedger.Domain.Account", b =>
                {
                    b.HasOne("TransactionLedger.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_Users");
                });

            modelBuilder.Entity("TransactionLedger.Domain.Transaction", b =>
                {
                    b.HasOne("TransactionLedger.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Accounts");

                    b.HasOne("TransactionLedger.Domain.Transaction", null)
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Transactions_Reverses");
                });
#pragma warning restore 612, 618
        }
    }
}
